# Generated by Django 5.0.7 on 2024-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('readyfordelivery', 'Ready for delivery'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('notpickedup', 'Not picked up'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='new', max_length=50),
        ),
    ]
